name: Job A

# on:
#   workflow_dispatch:

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches:
      - main
  push:
    branches:   
      - main

jobs:
  A:
    runs-on: self-hosted
    steps:
      - run: echo "Job A running" && sleep 4

  job_1:
    runs-on:  self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
      - name: Run Fibonacci Task (Shell Script)
        run: |
          chmod +x run_fibonacci_2.sh
          ./run_fibonacci_2.sh

  job_2:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Fibonacci Task (Shell Script)
        run: |
          chmod +x run_fibonacci.sh
          ./run_fibonacci.sh
