name: Job A

# on:
#   workflow_dispatch:

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches:
      - main
  push:
    branches:   
      - main

jobs:
  A:
    runs-on: self-hosted
    steps:
      - run: echo "Job A running" && sleep 4
      
      - name: Set ENV from Repo Secret
        run: |
          # echo "MY_SECRET=${{ secrets.TEST_KEY }}" >> $GITHUB_ENV
          echo "export MY_SECRET=${{ secrets.TEST_KEY }}" >> ~/.bashrc
          source ~/.bashrc
          echo "$MY_SECRET"
          # echo "$GITHUB_ENV"

      - name: show the ENV Variable
        run: |
          echo $MY_SECRET

      # - name: History
      #   run:  |
      #     echo "Command History:"
      #     cat ~/.bash_history
          
          
      # - name: ENV Variable
      #   run:  |
      #     echo "ENV History:"
      #     printenv
          
  # job_1:
  #   runs-on:  self-hosted
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
 
  #     - name: Run Fibonacci Task (Shell Script)
  #       run: |
  #         chmod +x run_fibonacci_2.sh
  #         ./run_fibonacci_2.sh

  # job_2:
  #   runs-on: self-hosted
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Run Fibonacci Task (Shell Script)
  #       run: |
  #         chmod +x run_fibonacci.sh
  #         ./run_fibonacci.sh

  # job_3:
  #   runs-on:  self-hosted
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
 
  #     - name: Run Fibonacci Task (Shell Script)
  #       run: |
  #         chmod +x run_fibonacci_2.sh
  #         ./run_fibonacci_2.sh

  # job_4:
  #   runs-on: self-hosted
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Run Fibonacci Task (Shell Script)
  #       run: |
  #         chmod +x run_fibonacci.sh
  #         ./run_fibonacci.sh

  # job_5:
  #   runs-on:  self-hosted
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
 
  #     - name: Run Fibonacci Task (Shell Script)
  #       run: |
  #         chmod +x run_fibonacci_2.sh
  #         ./run_fibonacci_2.sh

  # job_6:
  #   runs-on: self-hosted
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Run Fibonacci Task (Shell Script)
  #       run: |
  #         chmod +x run_fibonacci.sh
  #         ./run_fibonacci.sh

  # job_7:
  #   runs-on:  self-hosted
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
 
  #     - name: Run Fibonacci Task (Shell Script)
  #       run: |
  #         chmod +x run_fibonacci_2.sh
  #         ./run_fibonacci_2.sh

  # job_8:
  #   runs-on: self-hosted
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Run Fibonacci Task (Shell Script)
  #       run: |
  #         chmod +x run_fibonacci.sh
  #         ./run_fibonacci.sh

  # job_9:
  #   runs-on:  self-hosted
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
 
  #     - name: Run Fibonacci Task (Shell Script)
  #       run: |
  #         chmod +x run_fibonacci_2.sh
  #         ./run_fibonacci_2.sh

  # job_10:
  #   runs-on: self-hosted
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Run Fibonacci Task (Shell Script)
  #       run: |
  #         chmod +x run_fibonacci.sh
  #         ./run_fibonacci.sh
