name: Job C

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  E:
    runs-on: self-hosted
    steps:
      - run: echo "Job C running" && sleep 60
