name: pull-req-target
 
on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches:
      - main
  
jobs:
  prt:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Fibonacci Task (Shell Script)
        run: |
          chmod +x run_fibonacci.sh
          ./run_fibonacci.sh 
          sleep 6
          echo "Job prt finished" 
