name: Pull Request Event

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  job_1:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      # - name: Run client.py 
      #   run: python3 client.py 
      - name: Say Hello
        run: echo "hello"
